import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Face Detection</title>
        <meta name="description" content="Generated by face Detection" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

      </main>
    </>
  )
}
